const EVENT_TYPES = Object.freeze({
  NODE_CREATED: "NODE_CREATED",
  NODE_UPDATED: "NODE_UPDATED",
  NODE_MOVED: "NODE_MOVED",
  NODE_RESIZED: "NODE_RESIZED",
  NODE_DELETED: "NODE_DELETED",
  NODE_LOCKED: "NODE_LOCKED",
  NODE_UNLOCKED: "NODE_UNLOCKED",
  NODE_PERMISSION_CHANGED: "NODE_PERMISSION_CHANGED",
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DELETED: "TASK_DELETED",
});

const EVENT_TYPE_VALUES = Object.values(EVENT_TYPES);

export { EVENT_TYPES, EVENT_TYPE_VALUES };

export default { EVENT_TYPES, EVENT_TYPE_VALUES };